### ISSUE TITLE
k8s pf9-kube role not authorizing on Ubuntu

### ISSUE THREAD

**Issue by joshkelly** [platform9/express#119]
Ubuntu 16.04 client

TASK [map-role : Assigning Role - pf9-kube] ************************************************************************************************************************************ fatal: [preheat01.tnt14-zone2.phl1 -> localhost]: FAILED! => {"access_control_allow_credentials": "true", "changed": false, "connection": "close", "content": "{\"message\":\"HostNotFound: Host b76ff75f-7a3d-4fda-b597-6afb3f7400fe not found\"}", "content_length": "79", "content_type": "application/json; charset=utf-8", "date": "Tue, 07 Aug 2018 22:16:14 GMT", "json": {"message": "HostNotFound: Host b76ff75f-7a3d-4fda-b597-6afb3f7400fe not found"}, "msg": "Status code was 404 and not [200]: HTTP Error 404: Not Found", "redirected": false, "server": "nginx/1.14.0", "status": 404, "url": "https://131.153.254.42/resmgr/v1/hosts/b76ff75f-7a3d-4fda-b597-6afb3f7400fe/roles/pf9-kube"}

b76ff75f-7a3d-4fda-b597-6afb3f7400fe is the correct UUID

**Comment by mmccarre** [comment]
Believe this is fixed already, will re-open this bug if see during testing

**Comment by justgotthis** [comment]
Running into this issue for https://s4n.platform9.horse

TASK [map-role : Assigning Role - pf9-kube] ***********************************************************************************************
Monday 30 December 2019  17:35:20 +0000 (0:00:00.301)       0:02:32.914 *******
fatal: [k8s-prom-01 -> localhost]: FAILED! => {"access_control_allow_credentials": "true", "changed": false, "connection": "close", "content": "{\"message\":\"HostNotFound: Host c0e7c8e8-3e3a-47b8-a48b-5e44bc04496c not found\"}", "content_length": "79", "content_type": "application/json; charset=utf-8", "date": "Mon, 30 Dec 2019 17:35:21 GMT", "elapsed": 0, "json": {"message": "HostNotFound: Host c0e7c8e8-3e3a-47b8-a48b-5e44bc04496c not found"}, "msg": "Status code was 404 and not [200]: HTTP Error 404: Not Found", "redirected": false, "server": "nginx/1.14.1", "status": 404, "url": "https://s4n.platform9.horse/resmgr/v1/hosts/c0e7c8e8-3e3a-47b8-a48b-5e44bc04496c/roles/pf9-kube"}

Looks like it is here:
- name: "Assigning Role - {{rolename}}"
  uri:
    url: "https://{{du_fqdn}}/resmgr/v1/hosts/{{host_id.stdout.strip()}}/roles/{{rolename}}"
    method: PUT
    body: "{{role_json.stdout.strip()}}"
    body_format: json
    validate_certs: False
    headers:
      Content-Type: "application/json"
      X-Auth-Token: "{{api_token.stdout.strip()}}"
  register: uri_result
  delegate_to: localhost
- debug: var=uri_result

Not too familiar with this but maybe the host is not added therefore it is not found. i checked resmgr and it is running on the DU so not sure what is wrong but seems like there may be a DU issue that brings this error up?

**Comment by justgotthis** [comment]
whoops, hosts were part of another du so cancelling
