### ISSUE TITLE
Add ability to create inventory from CSV file

### ISSUE THREAD

**Issue by jb4free** [platform9/express#153]
##### SUMMARY
As a user of pf9-express, I would like to be able to specify my hosts and relevant host information, IPs, roles, role config information in a csv for ease of use.  pf9-express should take this information and automatically create my inventory file cleanly.

##### ISSUE TYPE

 - Feature Idea

##### COMPONENT NAME

pf9-express

##### ANSIBLE VERSION

```
n/a
```

**Comment by mmccarre** [comment]
This was completed months ago in pull requested #176
