### ISSUE TITLE
Run pf9-express from MacOS

### ISSUE THREAD

**Issue by joshkelly** [platform9/express#156]
##### SUMMARY
Enable pf9-express to run natively on macos

##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME

pf9-express

##### ANSIBLE VERSION

```
ansible 2.6.3
```

##### OS / ENVIRONMENT

macos
##### STEPS TO REPRODUCE

```yaml
$ ./pf9-express -s
ASSERT : unsupported platform
```

##### EXPECTED RESULTS

Successfully run pf9-express

##### ACTUAL RESULTS

```
ASSERT : unsupported platform
```

**Comment by busterswt** [comment]
It would prob be best if this process relied on a virtualenv, that way there was no conflict with existing packages. Thoughts?

**Comment by busterswt** [comment]
Also, there is an issue on MacOS where Ansible tries to use the built-in interpreter and not the one the venv sets up. This requires the use of the extra var '--extra-vars="ansible_python_interpreter=$(which python)"' for any ansible-playbook command.

**Comment by jb4free** [comment]
This could be solved by https://github.com/platform9/express-cli

**Comment by jb4free** [comment]
I'm closing this as a won't do.  This is being implemented with express-cli

**Comment by mmccarre** [comment]
@jb4free Please link to the corresponding issue in express-cli so it can be found easily if this comes up again.
