### ISSUE TITLE
Express does not fully support secondary regions

### ISSUE THREAD

**Issue by mmccarre** [platform9/express#188]
##### SUMMARY

Express does not fully support secondary regions. The wait-for-convergence role only checks the primary region for hosts currently converging within a secondary region.

##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

wait-for-convergence role

##### STEPS TO REPRODUCE

Deploy a primary and secondary region. Attempt to enroll a K8s master or worker node in the secondary region.

**Comment by mmccarre** [comment]
Additional issue with the pre-flight checks. Temporary workaround is to set the management plane URL to the full address versus the primary region.


TASK [pre-flight-checks-openstack : validate DU global network settings have been configured] *****************************************************************************************
ok: [hv-cs-congress-dev-01 -> localhost]

TASK [pre-flight-checks-openstack : set_fact] *****************************************************************************************************************************************
fatal: [hv-cs-congress-dev-01]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: 'dict object' has no attribute 'neutron'\n\nThe error appears to have been in '/opt/pf9-express/roles/pre-flight-checks-openstack/tasks/main.yml': line 25, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- set_fact:\n  ^ here\n"}

**Comment by h00pz** [comment]
If attempting to autoregister hosts they get registered to the main DU and not the secondary.
Only option is to not autoregister and then configure in Clarity UI manually.

**Comment by mmccarre** [comment]
@h00pz was the region variable also set to the new region? The workaround I've seen work is the DU URL being set to the secondary region FQDN and the region variable also set to the secondary.

**Comment by h00pz** [comment]
> @h00pz was the region variable also set to the new region? The workaround I've seen work is the DU URL being set to the secondary region FQDN and the region variable also set to the secondary.

Tried this and it failed again 3.7.12 PMO
