### ISSUE TITLE
use du_fqdn instead of ctrl_ip

### ISSUE THREAD

**Issue by kphatak** [platform9/express#247]
##### SUMMARY

Since we are using ELB, pf9-express should be using du_fqdn instead of ctrl_ip
##### ISSUE TYPE

 - Bug Report

##### COMPONENT NAME

pf9-express

##### ANSIBLE VERSION

```
ansible 2.9.1
```

##### OS / ENVIRONMENT

ubuntu 16.04

##### STEPS TO REPRODUCE

```yaml

```

##### EXPECTED RESULTS

if there is an ELB in front of the controller, it needs to resolve each time calling the controller.

##### ACTUAL RESULTS

If one of the node is inaccessible, it will hang if we are using IP of controller.

**Comment by mmccarre** [comment]
@kphatak won't it be using the IP of the ELB which should load balance against nodes behind it? Do you have an example of where it failed?

**Comment by jb4free** [comment]
closed by #248
