### ISSUE TITLE
PMK nodes onboarding fails due to error "template error while templating string: no filter named 'changed' for Ansible 2.9.1

### ISSUE THREAD

**Issue by piyush271291** [platform9/express#254]
##### SUMMARY
PMK nodes onboarding fails with the error - 

```FAILED! => {"msg": "The conditional check 'devpts_result|changed' failed. The error was: template error while templating string: no filter named 'changed'. String: {% if devpts_result|changed %} True {% else %} False {% endif %}\n\nThe error appears to be in '/opt/pf9-express/roles/common/tasks/redhat.yml': line 18, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Remount devpts mount point\n  ^ here\n"}```

##### ISSUE TYPE
 - Bug Report
 

##### ANSIBLE VERSION

```
ansible 2.9.1
  config file = /opt/pf9-express/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /bin/ansible
  python version = 2.7.5 (default, Aug  7 2019, 00:51:29) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
```

##### OS / ENVIRONMENT
CentOS Linux release 7.5.1804 (Core)

##### STEPS TO REPRODUCE
running pf9-express to onboard a PMK node 

./pf9-express -a k8s_master

##### EXPECTED RESULTS
pf9-express to complete successful onboarding of node. 
##### ACTUAL RESULTS

```
TASK [common : Remount devpts mount point] *****************************************************************************************************************************************************************
Sunday 15 December 2019  14:29:39 +0000 (0:00:00.656)       0:00:11.716 *******
fatal: [cv01]: FAILED! => {"msg": "The conditional check 'devpts_result|.changed' failed. The error was: template error while templating string: expected token 'name', got '.'. String: {% if devpts_result|.changed %} True {% else %} False {% endif %}\n\nThe error appears to be in '/opt/pf9-express/roles/common/tasks/redhat.yml': line 18, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Remount devpts mount point\n  ^ here\n"}
```

I was able to fix it by  changing line 20 of /opt/pf9-express/roles/common/tasks/redhat.yml to 

`when: devpts_result.changed`

**Comment by mmccarre** [comment]
@piyush271291 I'd propose we actually rip this task out. It's pre-1.0 for Express and doesn't appear needed at all. I noted this in issue #236.
